description: Ressource Geodatas
get:
  description: Obtenir une liste de données géographiques.
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {
                "Commune": "Neuchâtel",
                "NPA": 2000,
                "Canton": "NE"
              },
              {
                "Commune": "Yverdon-les-Bains",
                "NPA": 1400,
                "Canton": "VD"
              }
            ]