description: Ressource Geodatas
get:
  description: Obtenir une liste de données géographiques.
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {},
              {},
              {},
              {},
              {},
            ]