#%RAML 0.8
---
title: API Resource
baseUri: https://directhaircut.ch/api/
protocols: [HTTPS]
mediaType: application/json

traits:
  - auth: !include _traits/auth.raml

/users: !include users.raml

/staffs: !include staffs.raml

/notifications: !include notifications.raml

/businesses: !include businesses.raml

/prestations: !include prestations.raml

/schedules: !include schedules.raml

/rendezvous: !include rendezvous.raml

/geodatas: !include geodatas.raml

