description: User resource.
get:
  is: [auth: { roles: 'staff' }]
  description: Obtenir une liste d'utilisateur.
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {
                "id": "54d8ae163fd30364605c81a4",
                "firstname": "Romain",
                "lastname": "Terieur",
                "email": "mail@mail.com",
                "dateOfBirth": "",
                "gender": "homme",
                "roles": [
                  "user", "staff"
                ],
                "staffId": "54d8ae163fd30364605c81a5",
                "businessId": "54d8ae163fd30364605b45b5",
                "phone": "+41 79 123 45 67",
                "mobile": "+41 79 123 45 67",
                "city": "Neuchâtel",
                "street": "une rue",
                "canton": "NE",
                "zip": "2000",
                "imageProfileURL": "userPlaceholder.png"
              },
              {
                "id": "54d8ae163fd30364605c81a9",
                "firstname": "Christophe",
                "lastname": "Deplane",
                "email": "mail@mail.com",
                "dateOfBirth": "",
                "gender": "homme",
                "roles": [
                  "user"
                ],
                "phone": "+41 79 123 45 67",
                "mobile": "+41 79 123 45 67",
                "city": "Neuchâtel",
                "street": "une rue",
                "canton": "NE",
                "zip": "2000",
                "imageProfileURL": "userPlaceholder.png"
              },
            ]
post:
  description: Créer un nouvel utilisateur.
  body:
    application/json:
      example: |
        {
          "password": "mdp"
          "firstname": "Admin",
          "lastname": "Admin",
          "email": "admin@admin.com",
          "dateOfBirth": "1992-11-06T00:00:00.000Z",
          "gender": "homme",
          "phone": "+41 79 123 45 67",
          "mobile": "+41 79 123 45 67",
          "city": "Neuchâtel",
          "street": "Avenue du Premier Mars 1",
          "canton": "NE",
          "zip": "2000",
          "imageProfileURL": "userPlaceholder.png"
        }
  responses:
    201:
      body:
        application/json:
          example: |
            {
              "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NThkNGRmZGE5MWU5OTdjMTZjM2M0NGUiLCJpYXQiOjE0MzUzMjM5MDEyODMsImV4cCI6MTQzNTM3NzkwMTI4M30.ldu497Os0Q2dzbF6pDHvTcFlgGdVrnK-pknAWaJ3_Mo"
            }

/manager:
  post:
    description: Créer un nouvel utilisateur avec le rôle de manager.
    body:
      application/json:
        example: |
          {
            "password": "mdp"
            "firstname": "Admin",
            "lastname": "Admin",
            "email": "admin@admin.com",
            "dateOfBirth": "1992-11-06T00:00:00.000Z",
            "gender": "homme",
            "phone": "+41 79 123 45 67",
            "mobile": "+41 79 123 45 67",
            "city": "Neuchâtel",
            "street": "Avenue du Premier Mars 1",
            "canton": "NE",
            "zip": "2000",
            "imageProfileURL": "userPlaceholder.png"
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NThkNGRmZGE5MWU5OTdjMTZjM2M0NGUiLCJpYXQiOjE0MzUzMjM5MDEyODMsImV4cCI6MTQzNTM3NzkwMTI4M30.ldu497Os0Q2dzbF6pDHvTcFlgGdVrnK-pknAWaJ3_Mo"
              }

/me:
  get:
    is: [auth: { roles: 'user' }]
    description: Obtenir mon profil d'utilisateur.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "_id": "558d4dfda91e997c16c3c44e",
                "name": "Admin Admin",
                "email": "admin@admin.com",
                "age": 22,
                "gender": "homme",
                "phone": "+41 000 00 00",
                "mobile": "+41 000 00 01",
                "city": "Neuchâtel",
                "street": "Avenue du Premier Mars 1",
                "canton": "NE",
                "zip": 2000,
                "imageProfileUrl": "userPlaceholder.png",
                "roles": [
                  "user",
                  "staff",
                  "manager"
                ],
                "staffId": "558d5010a91e997c16c3c457",
                "preferences": {
                  "homeDisplay": "list"
                }
              }
  put:
    is: [auth: {roles: 'user'} ]
    description: Mettre à jour mon profil d'utilisateur.
    body:
      application/json:
        example: |
          {
            "phone": "+41 000 00 00"
            "mobile": "+41 000 00 00"
            "imageProfileURL": "image.png"
            "zip": "2000"
            "city": "Neuchâtel"
            "canton": "NE"
            "street": "Avenue du Premier Mars 1"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Profil utilisateur modifié avec succès."
              }

/{userId}:
  get:
    is: [auth: {roles: 'any'} ]
    description: Retrouver les détails d'un utilisateur spécifique.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "utilisateur": {
                  "_id": "558d4dfda91e997c16c3c44e",
                  "name": "Admin Admin",
                  "email": "admin@admin.com",
                  "age": 22,
                  "gender": "homme",
                  "phone": "+41 000 00 00",
                  "mobile": "+41 000 00 00",
                  "city": "Neuchâtel",
                  "street": "Avenue du Premier Mars 1",
                  "canton": "NE",
                  "zip": 2000,
                  "imageProfileUrl": "userPlaceholder.png"
                }
              }

  delete:
    is: [auth: {roles: 'admin'} ]
    description: Supprimer un utilisateur spécifique.
    responses:
      204:
        body:

/{userId}/password:
  put:
    is: [auth: {roles: 'user'} ]
    description: Modifier mon mot de passe.
    body:
      application/json:
        example: |
          {
            "oldPassword": "oldpass",
            "newPassword": "newpass"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Votre mot de passe a été changé avec succès."
              }

/{userId}/email:
  put:
    is: [auth: {roles: 'user'} ]
    description: Modifier mon adresse email.
    body:
      application/json:
        example: |
          {
            "email": "new@email.com"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Votre email a été changé avec succès."
              }

/{userId}/prefFavorite:
  put:
    is: [auth: {roles: 'user'} ]
    description: Mettre à jour mon salon favori.
    body:
      application/json:
        example: |
          {
            "favorite" : "55894f7134f23c9410420f73"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message" : "Votre salon favoris ont été mit à jours avec succès."
              }