headers:
  x-user-id:
    displayName: Authentication header
    description: |
      Use this header to specify the authentication.

      **roles required:** `<<roles>>`
    type: string
    example: |
      Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NThkNGRmZGE5MWU5OTdjMTZjM2M0NGUiLCJpY
      XQiOjE0MzUzMjM5MDEyODMsImV4cCI6MTQzNTM3NzkwMTI4M30.ldu497Os0Q2dzbF6pDHvTcFlgGdVrnK-pknAWaJ3_Mo
